import { StyleSheet } from 'react-native';

const AppStyles = StyleSheet.create({
  container: {
    padding: 20,
    backgroundColor: '#f0f4f7',
    marginBottom: 15,
  },
  heading: {
    fontSize: 35,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    color: '#333',
  },
  label: {
    fontSize: 20,
    fontWeight: 'bold',
    marginVertical: 8,
    color: '#000',
  },
  input: {
    borderWidth: 3,
    borderColor: '#ddd',
    borderRadius: 15,
    padding: 10,
    fontSize: 20,
    backgroundColor: '#fff',
    marginBottom: 15,
    color: '#000',
  },
  button: {
    backgroundColor: '#1E90FF',
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  message: {
    textAlign: 'center',
    marginTop: 15,
    fontSize: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2c3e50',
    textAlign: 'center',
    marginVertical: 10,
    color: '#000',
  },
  text: {
    fontSize: 16,
    color: '#34495e',
    textAlign: 'center',
    marginVertical: 5,
    lineHeight: 22,
  },
  // New styles for LoginComponent
  loginContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    backgroundColor: '#f0f4f7',
    paddingTop: '10%',
    paddingBottom: '10%',
    minHeight: '100%',
  },
  loginTitle: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 10,
  },
  loginInput: {
    height: 50,
    borderColor: '#ddd',
    borderWidth: 3,
    borderRadius: 8,
    paddingHorizontal: 15,
    fontSize: 20,
    marginBottom: 15,
    backgroundColor: '#fff',
    width: '80%',
    textAlign: 'center',
    justifyContent: 'center',
    color: '#000',
  },
  loginButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 10,
    borderRadius: 15,
    alignItems: 'center',
    marginTop: 20,
    padding: 10,
    width: '80%',
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
});

export default AppStyles;