import { StyleSheet } from 'react-native';

const AppStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#f0f4f7',
    justifyContent: 'center',
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  title: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 20,
  },
  label: {
    fontSize: 18,
    fontWeight: 'bold',
    marginVertical: 8,
    color: '#000',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 10,
    fontSize: 16,
    backgroundColor: '#fff',
    marginBottom: 15,
    color: '#000',
  },
  picker: {
    height: 50,
    width: '100%',
    marginBottom: 15,
  },
  button: {
    backgroundColor: '#4CAF50',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  text: {
    fontSize: 16,
    color: '#34495e',
    textAlign: 'center',
    marginVertical: 5,
    lineHeight: 22,
  },
  imagePreview: {
    width: 100,
    height: 100,
    resizeMode: 'cover',
    borderRadius: 8,
    marginTop: 10,
    alignSelf: 'center',
  },
  documentContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  documentText: {
    fontSize: 16,
    color: '#34495e',
    marginLeft: 10,
  },
  loginContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    backgroundColor: '#f0f4f7',
    paddingTop: '10%',
    paddingBottom: '10%',
    minHeight: '100%',
  },
  loginTitle: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 10,
  },
  loginInput: {
    height: 50,
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 15,
    fontSize: 16,
    marginBottom: 15,
    backgroundColor: '#fff',
    width: '80%',
    textAlign: 'center',
    justifyContent: 'center',
    color: '#000',
  },
  loginButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 20,
    padding: 10,
    width: '80%',
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  photoText: {
    fontSize: 16,
    color: '#34495e',
    textAlign: 'center',
    marginVertical: 5,
    lineHeight: 22,
  },
  displayContainer: {
    flex: 1,
    padding: 16,
    backgroundColor: '#fff',
    marginBottom: 15,
  },
  displayContent: {
    padding: 16,
  },
  displayHeader: {
    fontSize: 35,
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  displaySection: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderColor: '#ddd',
    paddingBottom: 10,
  },
  displaySectionHeader: {
    fontSize: 30,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  displayTable: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    marginBottom: 16,
    backgroundColor: '#fff',
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  displayRow: {
    flexDirection: 'row',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderColor: '#ddd',
  },
  displayCellHeader: {
    fontWeight: 'bold',
    width: '50%',
    paddingHorizontal: 8,
    fontSize: 19,
  },
  displayCell: {
    width: '50%',
    paddingHorizontal: 8,
    fontSize: 18,
  },
  displayPhotoContainer: {
    marginBottom: 20,
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  displayPhotoText: {
    fontSize: 16,
    marginBottom: 8,
    color: '#555',
  },
  displayPhotoPreview: {
    width: 100,
    height: 100,
    marginTop: 10,
  },
  displayTenantContainer: {
    marginBottom: 20,
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  displayLabel: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#555',
  },
  displayNoDataText: {
    fontSize: 16,
    color: '#999',
    textAlign: 'center',
    marginVertical: 10,
  },
  // New styles for ComplaintReplyDetails
  scrollView: {
    flexGrow: 1,
  },
  replyInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderTopWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fff',
  },
  replyInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 20,
    padding: 10,
    fontSize: 16,
    backgroundColor: '#fff',
    marginRight: 10,
  },
  replyButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
  },
  replyButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  adminReply: {
    alignSelf: 'flex-end',
    backgroundColor: '#d1e7ff',
    borderRadius: 10,
    padding: 10,
    marginVertical: 5,
    maxWidth: '80%',
  },
  userReply: {
    alignSelf: 'flex-start',
    backgroundColor: '#d4f7dc',
    borderRadius: 10,
    padding: 10,
    marginVertical: 5,
    maxWidth: '80%',
  },
  replyText: {
    fontSize: 16,
    color: '#333',
  },
  replyDate: {
    fontSize: 12,
    color: '#999',
    textAlign: 'right',
    marginTop: 5,
  },
  attachmentContainer: {
    padding: 10,
    backgroundColor: '#f9f9f9',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  attachmentHeader: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  attachmentText: {
    fontSize: 14,
    color: '#555',
  },
});

export default AppStyles;